// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gamfunk
NumericVector gamfunk(NumericVector epsmat, NumericMatrix gammat);
RcppExport SEXP pcIRT_gamfunk(SEXP epsmatSEXP, SEXP gammatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type epsmat(epsmatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type gammat(gammatSEXP);
    __result = Rcpp::wrap(gamfunk(epsmat, gammat));
    return __result;
END_RCPP
}
